config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "articles#index"
  # Defines the root path route ("/")
  devise_for :users
  root to: 'home#index'
  
  resources :warehouses, only: [:show, :create, :edit, :new, :update, :destroy]
  resources :suppliers, only: [:index, :show, :create, :edit, :new, :update]
  resources :product_models, only: [:index, :show, :new, :create, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update]  do
    resources :order_items, only: %i[ new create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items

  validates :name, :weight, :width, :height, :depth, :sku, :supplier_id, presence: true
  validates :width, :weight, :height, :depth, comparison: { greater_than: 0 }
  validates :sku, uniqueness: true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
    before_action :set_product_model, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:index]
    def index
        @product_models = ProductModel.all
    end

    def new
        @product_model = ProductModel.new()
    end

    def create
        @product_model = ProductModel.new(product_model_params)

        if @product_model.save
            return redirect_to product_model_path(@product_model.id), notice: 'Modelo de produto cadastrado com SUCESSO!'
        end

        flash.now[:notice] = 'Falha ao cadastrar! Preencha todos os campos.'
        render 'new'
    end

    def edit; end

    def update
        if @product_model.update(product_model_params)
            return redirect_to product_model_path(@product_model.id), notice: 'Modelo de produto cadastrado com SUCESSO!'
        end
        flash.now[:notice] =  'Falha ao atualizar! Preencha todos os campos.'
        render 'edit'
    end

    private
    def set_product_model
        @product_model = ProductModel.find(params[:id])
    end

    def product_model_params
        params.require(:product_model).permit(:name, :weight, :width,
        :height, :depth, :sku, :supplier_id)
    end
end

app/views/product_models/_form.html.erb
<%= form_with(model: @product_model) do |p| %>
    <div>
        <%= p.label :name %>
        <%= p.text_field :name %>
    </div>

    <div>
        <%= p.label :weight %>
        <%= p.text_field :weight %>
    </div>

    <div>
        <%= p.label :width %>
        <%= p.text_field :width %>
    </div>

    <div>
        <%= p.label :height %>
        <%= p.text_field :height %>
    </div>

    <div>
        <%= p.label :depth %>
        <%= p.text_field :depth %>
    </div>

    <div>
        <%= p.label :sku %>
        <%= p.text_field :sku %>
    </div>

    <div>
        <%= p.label :supplier_id %>
        <%= p.collection_select :supplier_id, Supplier.all, :id, :brand_name %>
    </div>

    <div>
        <%= p.submit 'Enviar' %>
    </div>

<% end %>

app/views/product_models/edit.html.erb
<% if @product_model.errors.any? %>
    <ul>
        <% @product_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<h1>Editar Modelo de Produto</h1>
<%= render 'form' %>

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>

<% if !@product_models.any?%>
    <div>
        <p>Não há produtos cadastrados!</p>
    </div>
<%end %>

<%= link_to 'Cadastrar produtos', new_product_model_path %>

<% @product_models.each do |p| %>
    <div>
        <h2><%= link_to p.name, product_model_path(p.id) %></h2>
        <dl>
            <dt>Marca: </dt>
            <dd><%= p.supplier.brand_name %></dd>
            <dt>SKU: </dt>
            <dd><%= p.sku %></dd>
        </dl>
    </div>
<% end %>

app/views/product_models/new.html.erb
<% if @product_model.errors.any? %>
    <ul>
        <% @product_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<h1>Novo Modelo de Produto</h1>
<%= render 'form' %>

app/views/product_models/show.html.erb
<h1>Modelo de Produto</h1>

<div>
    <h2><%= @product_model.name %></h2>
    <p><strong>Fornecedor:</strong> <%= @product_model.supplier.brand_name %></p>
    <p><strong>SKU:</strong> <%= @product_model.sku %></p>
    <p><strong>Dimensão</strong>: <%= @product_model.width %>cm x <%= @product_model.height %>cm x <%= @product_model.depth %>cm</p>
    <p><strong>Peso:</strong> <%= @product_model.weight %>g</p>
</div>

<%= link_to 'Editar', edit_product_model_path(@product_model.id) %>
<%= link_to 'Voltar', product_models_path %>