config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "articles#index"
  # Defines the root path route ("/")
  devise_for :users
  root to: 'home#index'
  
  resources :warehouses, only: [:show, :create, :edit, :new, :update, :destroy]
  resources :suppliers, only: [:index, :show, :create, :edit, :new, :update]
  resources :product_models, only: [:index, :show, :new, :create, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update]  do
    resources :order_items, only: %i[ new create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user
  has_many :order_items
  has_many :product_models, through: :order_items
  
  before_validation :code_generator

  validate :estimated_delivery_date_is_future
  validates :code, :estimated_delivery_date, presence: true

  enum status: { pending: 0, delivered: 5, canceled: 10 }, _default: :pending

  private
  def code_generator
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def estimated_delivery_date_is_future
    if self.estimated_delivery_date.present? && self.estimated_delivery_date <= Date.today
      self.errors.add(:estimated_delivery_date, 'Data deve ser futura.')
    end
  end
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :check_user, only: %i[show edit update delivered canceled]

    def index
        @orders = current_user.orders
    end

    def new
        @warehouses = Warehouse.all
        @suppliers = Supplier.all
        @order = Order.new()
    end

    def create
        order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
        @order = Order.new(order_params)
        @order.user = current_user
        if @order.save
            return redirect_to @order, alert: 'Pedido cadastrado com SUCESSO!'
        else
            @warehouses = Warehouse.all
            @suppliers = Supplier.all
            flash.now[:notice] = 'Não foi possível registrar o pedido.'
            render 'new'
        end
    end
    
    def show; end

    def edit
        @warehouses = Warehouse.all
        @suppliers = Supplier.all
    end

    def update
        order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
        @order.update(order_params)
        redirect_to @order, notice: 'Pedido atualizado com sucesso.'
    end
    
    def search
        @code = params[:query]
        @orders = Order.where("code LIKE ?", "%#{@code}%")
    end

    def delivered
        @order.delivered!
        return redirect_to @order
    end

    def canceled
        @order.canceled!
        return redirect_to @order
    end

    private
    def check_user
        @order = Order.find(params[:id])
        return redirect_to root_path, notice: "Você não possui acesso a esse pedido." if @order.user != current_user
    end
end

app/views/orders/_form.html.erb
<%= form_with(model: @order) do |f| %>
    <div>
        <%= f.label :warehouse_id, 'Galpão Destino' %>
        <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
    </div>

    <div>
        <%= f.label :supplier_id, 'Fornecedor' %>
        <%= f.collection_select :supplier_id, @suppliers, :id, :corporate_name %>
    </div>

    <div>
        <%= f.label :estimated_delivery_date, 'Data Prevista de Entrega' %>
        <%= f.date_field :estimated_delivery_date %>
    </div>

    <%= f.submit 'Gravar' %>
<% end %>

app/views/orders/_order.html.erb
<div>
    <dl>
        <dt><%= Order.human_attribute_name(:code) %>:</dt>
        <dd><%= link_to order.code, order_path(order) %></dd>

        <dt><%= Order.human_attribute_name(:warehouse_id) %>:</dd>
        <dd><%= order.warehouse.full_description %></dt>

        <dt><%= Order.human_attribute_name(:supplier_id) %>:</dt>
        <dd><%= order.supplier.brand_name %></dd>

        <dt><%= Order.human_attribute_name(:status) %>:</dt>
        <dd><%= t(order.status) %></dd>
    </dl>
</div>

app/views/orders/edit.html.erb
<% if @order.errors.any? %>
    <ul>
        <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<h1>Editar Pedido</h1>

<%= render 'form' %>

<%= link_to 'Voltar', root_path %>

app/views/orders/index.html.erb
<h1>Meus Pedidos</h1>

<% @orders.each do |order| %>
    <%= render order %>
<% end %>

app/views/orders/new.html.erb
<% if @order.errors.any? %>
    <ul>
        <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>


<h1>Registrar Pedido</h1>

<%= form_with(model: @order) do |f| %>
    <div>
        <%= f.label :warehouse_id, 'Galpão Destino' %>
        <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
    </div>

    <div>
        <%= f.label :supplier_id, 'Fornecedor' %>
        <%= f.collection_select :supplier_id, @suppliers, :id, :corporate_name %>
    </div>

    <div>
        <%= f.label :estimated_delivery_date, 'Data Prevista de Entrega' %>
        <%= f.date_field :estimated_delivery_date %>
    </div>

    <%= f.submit 'Gravar' %>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/orders/search.html.erb
<h1>Resultados da Busca por: <%= @code %></h1>
<p><%= @orders.count%> <%= Order.model_name.human(count: @orders.count) %> <%= t(:found, count: @orders.count) %></p>

<% @orders.each do |order| %>
    <%= render order %>
<% end %>

app/views/orders/show.html.erb
<h1>Detalhes do Pedido</h1>
<h2><%= Order.model_name.human %> <%= @order.code %></h2>

<dl>
    <dt><%= Order.human_attribute_name(:warehouse_id) %>:</dd>
    <dd><%= @order.warehouse.full_description %></dt>

    <dt><%= Order.human_attribute_name(:supplier_id) %>:</dt>
    <dd><%= @order.supplier.corporate_name %></dd>

    <dt><%= Order.human_attribute_name(:user) %>:</dt>
    <dd><%= @order.user.description %></dd>

    <dt><%= Order.human_attribute_name(:estimated_delivery_date) %>:</dt>
    <dd><%= I18n.localize(@order.estimated_delivery_date) %></dd>

    <dt><%= Order.human_attribute_name(:status) %>:</dt>
    <dd><%= t(@order.status) %></dd>
</dl>

<h2>Itens do Pedido<h2>

<% @order.order_items.each do |item| %>
    <%= item.quantity %> x <%= item.product_model.name %>
<% end %>

<%= link_to 'Adicionar Item', new_order_order_item_path(@order) %>

<% if !@order.delivered? %>
    <%= button_to 'Marcar como ENTREGUE', delivered_order_path(@order.id) %>
    <%= button_to 'Marcar como CANCELADO', canceled_order_path(@order.id) %>
<% end %>

<%= link_to 'Voltar', root_path %>
<%= link_to 'Editar', edit_order_path(@order) %>