config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "articles#index"
  # Defines the root path route ("/")
  devise_for :users
  root to: 'home#index'
  
  resources :warehouses, only: [:show, :create, :edit, :new, :update, :destroy]
  resources :suppliers, only: [:index, :show, :create, :edit, :new, :update]
  resources :product_models, only: [:index, :show, :new, :create, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update]  do
    resources :order_items, only: %i[ new create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    validates :corporate_name, :brand_name, :registration_number, :full_adress, :city, :state, :email, presence: true
    validates :corporate_name, :brand_name, :registration_number, :email, uniqueness: true
    validates :registration_number, length: { is: 13 }

    has_many :product_models 
    
    # validate :registration_number_can_or_cant_have_special_chars

    # def registration_number_can_or_cant_have_special_chars
    #     if !!!(registration_number =~ /\A[0-9]{2}[.][0-9]{3}[.][0-9]{3}[\/][0-9]{4}[-][0-9]{2}\z/) && !!!(registration_number =~ /\A[0-9]{2}[\.]?[0-9]{3}[\.]?[0-9]{3}[\/]?[0-9]{4}[-]?[0-9]{2}\z/)
    #         errors.add(:registration_number, "inválido")
    #     end
    #     if !!(registration_number =~ /\A[0-9]{2}[\.]?[0-9]{3}[\.]?[0-9]{3}[\/]?[0-9]{4}[-]?[0-9]{2}\z/) && !registration_number_includes_special(registration_number)
    #         errors.add(:registration_number, "inválido")
    #     end
    # end

    # def registration_number_includes_special(registration_number)
    #     special_chars_repetition = ['-', '.', '/'].map { |special| registration_number.count(special)}
    #     if [1,2,1] == special_chars_repetition || [0,0,0] == special_chars_repetition
    #         return true
    #     end
    #     return false
    # end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
    before_action :set_supplier, only: [:show, :edit, :update]

    def index
        @suppliers = Supplier.all
    end

    def show; end
    
    def new
        @supplier = Supplier.new()
    end

    def create
        @supplier = Supplier.new(supplier_params)

        if @supplier.save
            return redirect_to suppliers_path, notice: 'Fornecedor cadastrado com SUCESSO!'
        end

        flash.now[:notice] =  'Falha ao cadastrar! Preencha todos os campos.'
        render 'new'
    end

    def edit; end

    def update
        if @supplier.update(supplier_params)
            return redirect_to supplier_path(@supplier.id), notice: 'Fornecedor atualizado com sucesso!'
        end
        flash.now[:notice] =  'Falha ao atualizar! Preencha todos os campos.'
        render 'edit'
    end

    private
    def set_supplier
        @supplier = Supplier.find(params[:id])
    end

    def supplier_params
        params.require(:supplier).permit(:corporate_name, :brand_name, 
        :registration_number, :full_adress, 
        :city, :state, :email)
    end

end

app/views/suppliers/_form.html.erb
<%= form_with(model: @supplier) do |f| %>
    <div>
        <%= f.label :corporate_name %>
        <%= f.text_field :corporate_name %>
    </div>

    <div>
        <%= f.label :brand_name %>
        <%= f.text_field :brand_name %>
    </div>

    <div>
        <%= f.label :registration_number %>
        <%= f.text_field :registration_number %>
    </div>

    <div>
        <%= f.label :full_adress %>
        <%= f.text_field :full_adress %>
    </div>

    <div>
        <%= f.label :city%>
        <%= f.text_field :city %>
    </div>

    <div>
        <%= f.label :state %>
        <%= f.text_field :state %>
    </div>

    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div>
        <%= f.submit 'Enviar' %>
    </div>

<% end %>

app/views/suppliers/edit.html.erb
<% if @supplier.errors.any? %>
    <ul>
        <% @supplier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<h1>Editar Fornecedor <%= @supplier.brand_name %></h1>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h1>Fornecedores</h1>

<div>
    <%= link_to 'Cadastrar Fornecedor', new_supplier_path %>
</div>
<% if @suppliers.any? %>
    <table>
        <thead>
            <tr>
                <th>Nome</th>
                <th>Localização</th>
            </tr>
        </thead>
        <tbody>
            <% @suppliers.each do |s| %>
                <tr>
                    <td><%= link_to s.brand_name, supplier_path(s.id) %></td>
                    <td><%= s.city %>/<%= s.state %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <br>
<% else %>
    <p>Não há fornecedores cadastrados!</p>
<% end %>

app/views/suppliers/new.html.erb
<% if @supplier.errors.any? %>
    <ul>
        <% @supplier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<h1>Novo Fornecedor</h1>

<%= render 'form' %>
<%= link_to 'Voltar', suppliers_path %>

app/views/suppliers/show.html.erb
<h1>Fornecedor: <%= @supplier.brand_name%></h1>

<div>
    <p><strong>Razão Social: </strong><%= @supplier.corporate_name %></p>
    <p><strong>Nome Fantasia: </strong><%= @supplier.brand_name %></p>
    <p><strong>CNPJ: </strong><%= @supplier.registration_number %></p>
    <p><strong>Endereço: </strong><%= @supplier.full_adress %></p>
    <p><strong>Cidade: </strong><%= @supplier.city %></p>
    <p><strong>Estado: </strong><%= @supplier.state %></p>
    <p><strong>E-mail: </strong><%= @supplier.email %></p>
</div>

<div>
    <%= link_to 'Editar Fornecedor', edit_supplier_path(@supplier.id) %>
</div>

<div>
    <%= link_to 'Voltar', suppliers_path %>
</div>