config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "articles#index"
  # Defines the root path route ("/")
  devise_for :users
  root to: 'home#index'
  
  resources :warehouses, only: [:show, :create, :edit, :new, :update, :destroy]
  resources :suppliers, only: [:index, :show, :create, :edit, :new, :update]
  resources :product_models, only: [:index, :show, :new, :create, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update]  do
    resources :order_items, only: %i[ new create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" %>
    <link rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
     integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
     crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
    <%= link_to root_path do %>
      <h1>Galpões & Estoque</h1>
    <% end %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="https://github.com/muckagr/warehouse-app" target="blank">WarehouseApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav"> 
          <ul class="navbar-nav">
            <li class="nav-item active"><%= link_to 'Pagina Inicial', root_path, html_options = {class: "nav-link"} %></li>
            <li class="nav-item active"><%= link_to 'Fornecedores', suppliers_path, html_options = {class: "nav-link"} %></li>
            <li class="nav-item active"><%= link_to 'Modelos de Produtos', product_models_path, html_options = {class: "nav-link"} %></li>
            <li class="nav-item active"><%= link_to 'Meus Pedidos', orders_path, html_options = {class: "nav-link"} %></li>
            <li class="nav-item active"><%= link_to 'Registrar Pedido', new_order_path, html_options = {class: "nav-link"} %></li>
            <% if user_signed_in? %>
              <li class="nav-item active">
                <%= form_with url: search_orders_path, method: :get do |f| %>
                  <%= f.label :query, 'Buscar Pedido' %>
                  <%= f.text_field :query%>
                  <%= f.submit 'Buscar' %>
                <% end %>
              </li>
              <li class="nav-item active"><p class="nav-link"><%= current_user.description %></p></li>
              <li class="nav-item active"><%= button_to 'Deslogar', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li class="nav-item active"><%= link_to 'Fazer login', new_user_session_path, html_options = {class: "nav-link"} %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <main>
    <div>
      <%= alert %>
      <%= notice %>
    </div>
      <%= yield %>
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>